"""init_db

Revision ID: 49488c07a7dc
Revises: 
Create Date: 2026-06-02 22:01:31.313644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49488c07a7dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confidence_log')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('idx_alerts_is_acknowledged'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('camera_rules')
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_events_camera_timestamp'), table_name='events')
    op.drop_index(op.f('idx_events_status_severity'), table_name='events')
    op.drop_constraint(op.f('events_camera_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'cameras', ['camera_id'], ['id'])
    op.drop_column('events', 'confidence')
    op.drop_column('events', 'person_id')
    op.drop_column('events', 'class_label')
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'video_clip_url')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('events', sa.Column('video_clip_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('class_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_camera_id_fkey'), 'events', 'cameras', ['camera_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_events_status_severity'), 'events', ['status', 'severity'], unique=False)
    op.create_index(op.f('idx_events_camera_timestamp'), 'events', ['camera_id', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('events', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table('camera_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('confidence_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.5'), autoincrement=False, nullable=True),
    sa.Column('time_window_seconds', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('camera_rules_camera_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('camera_rules_pkey'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('vlm_verdict', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('alerts_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    op.create_index(op.f('idx_alerts_is_acknowledged'), 'alerts', ['is_acknowledged'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cpu_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ram_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gpu_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('telemetry_logs_camera_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('telemetry_logs_pkey'))
    )
    op.create_table('confidence_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('inference_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('environment_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_flagged_for_retrain', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('confidence_log_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('confidence_log_pkey'))
    )
    # ### end Alembic commands ###
